### 전체 폴더 조회
GET http://localhost:10243/api/folders

### 폴더명으로 모든 대시보드 이름 조회
GET http://localhost:10243/api/folders/name/sample

### 폴더명으로 모든 대시보드 데이터 조회
GET http://localhost:10243/api/folders/sample

### 차트 조회
GET http://localhost:10243/api/folders/a/dashboards/aGRAPH/chart

### 차트 이름 조회
GET http://localhost:10243/api/folders/a/dashboards/aGRAPH/chart/name

### 차트의 개수와 on/off 필터링
GET http://localhost:10243/api/folders/a/dashboards/aGRAPH/filtered-chart?filter=chart-a:off