### 전체 폴더 조회
GET http://localhost:10243/api/folders

### 폴더명으로 모든 대시보드 이름 조회
GET http://localhost:10243/api/f/name/sample

### 폴더명으로 모든 대시보드 데이터 조회
GET http://localhost:10243/api/f/sample

### 차트 조회
GET http://localhost:10243/api/f/sample/d/grafana/c

### 차트 이름 조회
GET http://localhost:10243/api/f/sample/d/grafana/c/name

### 차트의 개수와 on/off 필터링
GET http://localhost:10243/api/f/sample/d/grafana/filtered-chart?filter=cGRAPH:off